package com.example.application.mapper;

import com.example.application.entity.GarbageDO;

import java.util.List;

public interface GarbageDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list
     *
     * @mbg.generated Sun Sep 22 21:46:53 CST 2019
     */
    List<GarbageDO> selectGarbageByName(String name);

    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list
     *
     * @mbg.generated Sun Sep 22 21:46:53 CST 2019
     */
    int insert(GarbageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list
     *
     * @mbg.generated Sun Sep 22 21:46:53 CST 2019
     */
    int insertSelective(GarbageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list
     *
     * @mbg.generated Sun Sep 22 21:46:53 CST 2019
     */
    GarbageDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list
     *
     * @mbg.generated Sun Sep 22 21:46:53 CST 2019
     */
    int updateByPrimaryKeySelective(GarbageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list
     *
     * @mbg.generated Sun Sep 22 21:46:53 CST 2019
     */
    int updateByPrimaryKey(GarbageDO record);
}