package com.example.application.entity;

public class GarbageDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column list.id
     *
     * @mbg.generated Sun Sep 22 21:46:53 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column list.name
     *
     * @mbg.generated Sun Sep 22 21:46:53 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column list.belong
     *
     * @mbg.generated Sun Sep 22 21:46:53 CST 2019
     */
    private String belong;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column list.id
     *
     * @return the value of list.id
     *
     * @mbg.generated Sun Sep 22 21:46:53 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column list.id
     *
     * @param id the value for list.id
     *
     * @mbg.generated Sun Sep 22 21:46:53 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column list.name
     *
     * @return the value of list.name
     *
     * @mbg.generated Sun Sep 22 21:46:53 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column list.name
     *
     * @param name the value for list.name
     *
     * @mbg.generated Sun Sep 22 21:46:53 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column list.belong
     *
     * @return the value of list.belong
     *
     * @mbg.generated Sun Sep 22 21:46:53 CST 2019
     */
    public String getBelong() {
        return belong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column list.belong
     *
     * @param belong the value for list.belong
     *
     * @mbg.generated Sun Sep 22 21:46:53 CST 2019
     */
    public void setBelong(String belong) {
        this.belong = belong == null ? null : belong.trim();
    }
}